# Generated by Django 5.2 on 2025-05-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaitem',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categoriaitem',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemloja',
            name='tipo',
            field=models.CharField(choices=[('camisa', 'Camisa'), ('camiseta', 'Camiseta'), ('calcao', 'Calção'), ('basquete', 'Camisa de Basquete')], max_length=10),
        ),
    ]
