# Generated by Django 5.2 on 2025-05-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_loja_itemloja_loja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemloja',
            old_name='imagem',
            new_name='imagem_preview',
        ),
    ]
