# Generated by Django 5.2 on 2025-05-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_rename_imagem_itemloja_imagem_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemloja',
            name='telefone',
            field=models.CharField(blank=True, help_text='Número no formato +5583999999999', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemloja',
            name='whatsapp_link',
            field=models.CharField(blank=True, help_text='Link completo do WhatsApp (opcional)', max_length=255, null=True),
        ),
    ]
