# Generated by Django 5.2 on 2025-05-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_itemloja_telefone_itemloja_whatsapp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemloja',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemloja',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
