# Generated by Django 5.2 on 2025-05-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_alter_itemloja_telefone_alter_itemloja_whatsapp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='cor_primaria',
            field=models.CharField(default='#6c757d', help_text='Cor primária no formato HEX (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='loja',
            name='cor_secundaria',
            field=models.CharField(default='#495057', help_text='Cor secundária no formato HEX (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='loja',
            name='cor_texto',
            field=models.CharField(default='#ffffff', help_text='Cor do texto no formato HEX (#RRGGBB)', max_length=7),
        ),
    ]
