# Generated by Django 5.2 on 2025-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_loja_cor_primaria_loja_cor_secundaria_loja_cor_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemloja',
            name='tipo',
            field=models.CharField(choices=[('camisa', 'Camisa'), ('camiseta', 'Camiseta'), ('calcao', 'Calção'), ('basquete', 'Camisa de Basquete'), ('acessorios', 'Acessórios'), ('games', 'Games')], max_length=10),
        ),
    ]
