# Generated by Django 5.2 on 2025-05-15 21:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_itemloja_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemloja',
            name='imagem_preview',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='itens_lojas'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='logos_lojas'),
        ),
    ]
