# Generated by Django 5.2 on 2025-05-16 00:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_alter_itemloja_imagem_preview_alter_loja_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemloja',
            name='imagem_preview',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
    ]
