# Generated by Django 5.2 on 2025-05-16 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0011_alter_itemloja_imagem_preview_alter_loja_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemloja',
            name='tipo_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.tipoitem'),
        ),
    ]
