# Generated by Django 5.2 on 2025-05-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_tipoitem_itemloja_tipo_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemloja',
            name='tipo_item',
        ),
        migrations.DeleteModel(
            name='TipoItem',
        ),
    ]
