# Generated by Django 5.2 on 2025-06-07 18:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0013_remove_itemloja_tipo_item_delete_tipoitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemloja",
            name="descricao",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
