# Generated by Django 5.2 on 2025-04-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoPIX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chave_pix', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20)),
                ('codigo_transacao', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
