# Generated by Django 5.2 on 2025-04-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentopix',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='pagamentopix',
            name='chave_pix',
            field=models.CharField(default='hiaguinhospencer@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagamentopix',
            name='destinatario',
            field=models.CharField(default='Hiago José de Souza', max_length=100),
        ),
        migrations.AlterField(
            model_name='pagamentopix',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
    ]
