# Generated by Django 5.2 on 2025-05-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_pagamentopix_qr_code_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentopix',
            name='cidade',
            field=models.CharField(default='Areia Branca', max_length=100),
        ),
    ]
