# Generated by Django 5.2 on 2025-05-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_pagamentopix_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentopix',
            name='chave_pix',
            field=models.CharField(default='hiagosouzadev10@gmail.com', max_length=100),
        ),
    ]
