version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7
    command: redis-server --requirepass emillylinda10
    ports:
      - "6379:6379"
    restart: always

  celery:
    build: .
    command: celery -A bolao_virtual worker --loglevel=info
    restart: always
    volumes:
      - .:/app
      - static:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - redis
      - web


  web:
    build: .
    volumes:
      - .:/app
      - static:/app/staticfiles
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    restart: always
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web

volumes:
  postgres_data:
  static:
