version: '3.8'

services:

  redis:
    image: redis:7
    restart: always

  celery:
    build: .
    command: celery -A bolao_virtual worker --loglevel=info
    restart: always
    volumes:
      - static:/static
      - media:/media
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - redis


  web:
    build: .
    command: gunicorn bolao_virtual.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static:/app/staticfiles
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always


volumes:
  static:
  media:
