# Generated by Django 5.2 on 2025-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiacaoBolao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primerio_lugar', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('segundo_lugar', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('terceiro_lugar', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
            ],
        ),
    ]
