# Generated by Django 5.2 on 2025-05-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_premiacaobolao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiacaobolao',
            old_name='primerio_lugar',
            new_name='primeiro_lugar',
        ),
    ]
