# Generated by Django 5.2 on 2025-05-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_primerio_lugar_premiacaobolao_primeiro_lugar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiacaobolao',
            old_name='primeiro_lugar',
            new_name='premiacao',
        ),
        migrations.RemoveField(
            model_name='premiacaobolao',
            name='segundo_lugar',
        ),
        migrations.RemoveField(
            model_name='premiacaobolao',
            name='terceiro_lugar',
        ),
        migrations.AddField(
            model_name='premiacaobolao',
            name='posicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
