# Generated by Django 5.2 on 2025-04-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='moedas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
