# Generated by Django 5.2 on 2025-05-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_moedas_usuario_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='xp_para_proximo_level',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
