# Generated by Django 5.2 on 2025-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_level_usuario_xp_para_proximo_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel_maximo',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
