# Generated by Django 5.2 on 2025-05-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_nivel_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='moedas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nivel_maximo',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pagamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp_para_proximo_level',
            field=models.PositiveIntegerField(default=500),
        ),
    ]
