# Generated by Django 5.2 on 2025-05-06 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_userprofile_level_userprofile_moedas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DestaqueDaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertos', models.PositiveIntegerField()),
                ('total_jogos', models.PositiveIntegerField(default=10)),
                ('dica_do_mestre', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rodada')),
            ],
            options={
                'ordering': ['-rodada'],
                'unique_together': {('rodada', 'usuario')},
            },
        ),
    ]
