# Generated by Django 5.2 on 2025-05-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rodada_destaquedasemana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destaquedasemana',
            name='acertos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destaquedasemana',
            name='total_jogos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
