# Generated by Django 5.2 on 2025-05-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_destaquedasemana_acertos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rodada',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
