# Generated by Django 5.2 on 2025-05-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_rodada_data_fim_alter_rodada_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destaquedasemana',
            name='rodada',
            field=models.IntegerField(),
        ),
    ]
