# Generated by Django 5.2 on 2025-05-15 20:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_destaquedasemana_rodada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
    ]
