# Generated by Django 5.2 on 2025-07-14 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0010_alter_usuario_foto_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Convite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                ("data_aceito", models.DateTimeField(blank=True, null=True)),
                (
                    "convidado",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="convite_recebido",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "convidador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convites_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
