# Generated by Django 5.2 on 2025-07-14 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0012_recompensapremium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convite",
            name="convidado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="convite_recebido",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
