# Generated by Django 5.2 on 2025-07-14 23:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0013_alter_convite_convidado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convite",
            name="codigo",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
