# Generated by Django 5.2 on 2025-09-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "usuarios",
            "0015_remove_convite_convidador_remove_convite_data_envio_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convite",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="convite",
            name="convidado",
        ),
        migrations.DeleteModel(
            name="CodigoConvite",
        ),
        migrations.DeleteModel(
            name="Convite",
        ),
    ]
