# Generated by Django 5.2 on 2025-05-05 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_voto', models.DateTimeField(auto_now_add=True)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidade.enquete')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidade.opcaoenquete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'enquete')},
            },
        ),
    ]
