# Generated by Django 5.2 on 2025-05-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0003_votoenquete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votoenquete',
            options={'verbose_name': 'Voto de Enquete', 'verbose_name_plural': 'Votos de Enquetes'},
        ),
    ]
