# Generated by Django 5.2 on 2025-05-05 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0004_alter_votoenquete_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioforum',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comunidade.comentarioforum'),
        ),
    ]
