# Generated by Django 5.2 on 2025-04-29 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_casa', models.PositiveSmallIntegerField()),
                ('placar_visitante', models.PositiveSmallIntegerField()),
                ('data_palpite', models.DateTimeField(auto_now_add=True)),
                ('pontos_ganhos', models.PositiveSmallIntegerField(default=0)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partida')),
            ],
            options={
                'ordering': ['-data_palpite'],
            },
        ),
    ]
