# Generated by Django 5.2 on 2025-05-01 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloquearPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada_bloqueada', models.BooleanField(default=False)),
                ('bloquear_grafico', models.BooleanField(default=False)),
                ('bloquear_pagamento', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada_atual', models.IntegerField(default=1)),
                ('time_casa', models.CharField(max_length=50)),
                ('placar_casa', models.CharField(blank=True, null=True)),
                ('time_visitante', models.CharField(max_length=50)),
                ('placar_visitante', models.CharField(blank=True, null=True)),
                ('imagem_casa', models.ImageField(upload_to='emblemas_times')),
                ('imagem_fora', models.ImageField(upload_to='emblemas_times')),
                ('preenchido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RodadaOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada_atual', models.IntegerField(default=1)),
                ('time_casa', models.CharField(max_length=50)),
                ('placar_casa', models.IntegerField(default=0)),
                ('time_visitante', models.CharField(max_length=50)),
                ('placar_visitante', models.IntegerField(default=0)),
                ('vencedor', models.CharField(max_length=50)),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='palpite',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='palpite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='palpite',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='palpite',
            name='imagem_casa',
            field=models.ImageField(blank=True, null=True, upload_to='emblemas_times'),
        ),
        migrations.AddField(
            model_name='palpite',
            name='imagem_fora',
            field=models.ImageField(blank=True, null=True, upload_to='emblemas_times'),
        ),
        migrations.AddField(
            model_name='palpite',
            name='placar_exato',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='palpite',
            name='rodada_atual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='palpite',
            name='time_casa',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palpite',
            name='time_visitante',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palpite',
            name='tipo_class',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='palpite',
            name='vencedor',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palpite',
            name='vitorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='placar_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='placar_visitante',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='palpite',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0)),
                ('placar_exato', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('posicao_atual', models.IntegerField(blank=True, null=True)),
                ('posicao_anterior', models.IntegerField(blank=True, null=True)),
                ('posicao_variacao', models.IntegerField(blank=True, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='palpite',
            name='data_palpite',
        ),
        migrations.RemoveField(
            model_name='palpite',
            name='partida',
        ),
        migrations.RemoveField(
            model_name='palpite',
            name='pontos_ganhos',
        ),
    ]
