# Generated by Django 5.2 on 2025-05-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0004_bloquearpartida_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquearpartida',
            name='rodada_atual',
            field=models.IntegerField(default=1),
        ),
    ]
