# Generated by Django 5.2 on 2025-05-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0005_bloquearpartida_rodada_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquearpartida',
            name='data_final',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
