# Generated by Django 5.2 on 2025-05-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0006_bloquearpartida_data_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquearpartida',
            name='partida_atual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bloquearpartida',
            name='partida_final',
            field=models.IntegerField(default=39),
        ),
    ]
