# Generated by Django 5.2 on 2025-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0007_bloquearpartida_partida_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palpite',
            name='data_jogo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rodada',
            name='data_jogo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rodadaoriginal',
            name='data_jogo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
