# Generated by Django 5.2 on 2025-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0009_pontuacaorodada'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBolao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_final', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
