# Generated by Django 5.2 on 2025-05-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0010_databolao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rodada', models.IntegerField(unique=True)),
                ('editar_rodada', models.BooleanField(default=False)),
            ],
        ),
    ]
