# Generated by Django 5.2 on 2025-05-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpites', '0011_configuracaorodada'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorodada',
            name='data_limite_edicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaorodada',
            name='numero_rodada',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
