# Generated by Django 5.2 on 2025-06-02 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palpites", "0012_configuracaorodada_data_limite_edicao_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampeaoBolao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pontos", models.PositiveIntegerField()),
                ("edicao", models.CharField(max_length=50)),
                ("data_coroado", models.DateField(auto_now_add=True)),
                ("titulos_conquistados", models.PositiveIntegerField(default=1)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campeonatos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Campeões do Bolão",
                "ordering": ["-edicao"],
                "unique_together": {("usuario", "edicao")},
            },
        ),
    ]
