# Generated by Django 5.2 on 2025-04-29 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrofeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(max_length=50)),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('cor', models.CharField(default='#FFD700', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PremioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_premiacao', models.DateTimeField(auto_now_add=True)),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.BooleanField(default=False)),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premios.premio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetaConquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('placar_exato', 'Placar Exato'), ('pontos_rodada', 'Pontos em uma Rodada'), ('sequencia', 'Sequência de Acertos'), ('participacao', 'Participação em Rodadas'), ('top_ranking', 'Posição no Ranking')], max_length=20)),
                ('valor_requerido', models.PositiveIntegerField()),
                ('xp_recompensa', models.PositiveIntegerField(default=100)),
                ('moedas_recompensa', models.PositiveIntegerField(default=0)),
                ('tipo_trofeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premios.tipotrofeu')),
            ],
        ),
        migrations.CreateModel(
            name='ConquistaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conquista', models.DateTimeField(auto_now_add=True)),
                ('progresso_atual', models.PositiveIntegerField(default=0)),
                ('concluida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premios.metaconquista')),
            ],
            options={
                'unique_together': {('usuario', 'meta')},
            },
        ),
    ]
