# Generated by Django 5.2 on 2025-04-30 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0002_alter_metaconquista_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoConquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conquista', models.DateTimeField(auto_now_add=True)),
                ('xp_ganho', models.PositiveIntegerField()),
                ('moedas_ganhas', models.PositiveIntegerField()),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premios.metaconquista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
