# Generated by Django 5.2 on 2025-05-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0003_historicoconquista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaconquista',
            name='tipo',
            field=models.CharField(choices=[('placar_exato', 'Placar Exato'), ('pontos_rodada', 'Pontos em uma Rodada'), ('sequencia', 'Sequência de Acertos'), ('participacao', 'Participação em Rodadas'), ('top_ranking', 'Posição no Ranking'), ('pontos_totais', 'Pontos Totais Acumulados'), ('total_conquistas', 'Total de Conquistas Únicas'), ('rei_palpites', 'Rei dos Palpites'), ('colecionador', 'Colecionadoor de Troféus')], max_length=20),
        ),
    ]
