# Generated by Django 5.2 on 2025-05-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0004_alter_metaconquista_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoconquista',
            options={'ordering': ['-data_conquista']},
        ),
    ]
