# Generated by Django 5.2 on 2025-05-07 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0005_alter_historicoconquista_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('icone', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='premio',
            name='valor_maximo',
        ),
        migrations.RemoveField(
            model_name='premio',
            name='valor_minimo',
        ),
        migrations.AddField(
            model_name='premio',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='premio',
            name='estoque',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='premio',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='premios/'),
        ),
        migrations.AddField(
            model_name='premio',
            name='preco_moedas',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='premio',
            name='tipo',
            field=models.CharField(choices=[('titulo', 'Título/Apelido'), ('voucher', 'Voucher de Desconto'), ('produto', 'Produto Físico'), ('moeda', 'Moedas Extras')], default='titulo', max_length=20),
        ),
        migrations.AddField(
            model_name='premio',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='premios.categoriapremio'),
        ),
        migrations.CreateModel(
            name='PedidoPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('utilizado', models.BooleanField(default=False)),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premios.premio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TituloAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.ForeignKey(limit_choices_to={'premio__tipo': 'titulo'}, on_delete=django.db.models.deletion.CASCADE, to='premios.pedidopremio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
