# Generated by Django 5.2 on 2025-05-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0006_categoriapremio_remove_premio_valor_maximo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidopremio',
            name='codigo_voucher',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedidopremio',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidopremio',
            name='data_resgate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidopremio',
            name='data_utilizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidopremio',
            name='parceiro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedidopremio',
            name='url_parceiro',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pedidopremio',
            name='valor_desconto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
