# Generated by Django 5.2 on 2025-05-12 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_loja_cor_primaria_loja_cor_secundaria_loja_cor_texto'),
        ('premios', '0007_pedidopremio_codigo_voucher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidopremio',
            name='parceiro',
        ),
        migrations.AddField(
            model_name='pedidopremio',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.loja', verbose_name='Loja Parceira'),
        ),
    ]
