# Generated by Django 5.2 on 2025-05-12 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_loja_cor_primaria_loja_cor_secundaria_loja_cor_texto'),
        ('premios', '0008_remove_pedidopremio_parceiro_pedidopremio_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidopremio',
            name='loja',
        ),
        migrations.RemoveField(
            model_name='pedidopremio',
            name='url_parceiro',
        ),
        migrations.RemoveField(
            model_name='pedidopremio',
            name='valor_desconto',
        ),
        migrations.AddField(
            model_name='premio',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='premio',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loja.loja', verbose_name='Loja Parceira'),
        ),
        migrations.AddField(
            model_name='premio',
            name='url_parceiro',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='premio',
            name='valor_desconto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='premio',
            name='whatsapp_loja',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
