# Generated by Django 5.2 on 2025-05-15 21:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0009_remove_pedidopremio_loja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='imagem',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='premios'),
        ),
    ]
