# Generated by Django 5.2 on 2025-05-16 00:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0010_alter_premio_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='imagem',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
    ]
