# Generated by Django 5.2 on 2025-05-16 17:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0011_alter_premio_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premio',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem'),
        ),
    ]
