# Generated by Django 5.2 on 2025-06-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("premios", "0012_alter_premio_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("codigo", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="metaconquista",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="premios.tipometa"
            ),
        ),
    ]
